const constants={
// Table Names
MOVIE_TABLE:"STREAM_MOVIE",
CATEGORY_TABLE:"STREAM_CATEGORY",
USER_TABLE:"STREAM_USER",
ORDER_TABLE:"STREAM_ORDER",
PAYMENT_TABLE:"STREAM_PAYMENT",
PROMOTION_TABLE:"STREAM_PROMOTION",
FAVOURITE_TABLE:"STREAM_FAVOURITE",
PLAY_LIST_TABLE:"STREAM_PLAY_LIST",
SUCURSAL_TABLE:"STREAM_SUCURSAL",
PROFILE_TABLE:"STREAM_PROFILE",
LOGININFO_TABLE:"STREAM_LOGININFO",
WATCH_LIST_TABLE:"STREAM_WATCH_LIST",
VISIT_TABLE:"STREAM_VISITS",
CLIENT_TABLE:"STREAM_CLIENT",
WISH_LIST_TABLE:"STREAM_WISH_LIST",
VIEW_TABLE:"STREAM_VIEW_TABLE",
LAST_SEQUENCE_TABLE:"STREAM_LAST_SEQUENCE",
SUBSCRIPTION_TABLE:"STREAM_SUBSCRIPTION",

//EMAIL TEMPLATES
ORDER_SUCCESS_TEMPLATE: "STREAM_ORDER_SUCCESS_TEMPLATE",
ORDER_UPDATE_TEMPLATE: "STREAM_ORDER_UPDATE_TEMPLATE",

//EMAIL SUBJECTS
ORDER_CONFIRMATION_SUBJECT_PT: '[STREAMIT] Subscrição Confirmada! ',

}

module.exports=constants;